services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - analytics_net

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-analytics}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-analytics}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - analytics_net

  migrate:
    build:
      context: .
      target: migrate
    environment:
      - DB_DSN=${DB_DSN:-postgres://postgres:password@postgres:5432/analytics?sslmode=disable}
      - MIGRATIONS_DIR=/root/infra/migrations
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - analytics_net

  api:
    build:
      context: .
      target: api
    expose:
      - "8080"
    environment:
      - REDIS_DSN=redis://redis:6379
    depends_on:
      - redis
    networks:
      - analytics_net

  api_lb:
    image: haproxy:2.9-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./infra/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api
    networks:
      - analytics_net

  worker:
    build:
      context: .
      target: worker # <--- NOTE THIS (Uses the same code, different binary)
    # deploy:
    #   mode: replicated
    #   replicas: 5 # <--- Run 5 instances
    environment:
      - REDIS_DSN=redis://redis:6379
      - DB_DSN=${DB_DSN:-postgres://postgres:password@postgres:5432/analytics?sslmode=disable}
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    networks:
      - analytics_net

  cron:
    build:
      context: .
      target: cron
    environment:
      - DB_DSN=${DB_DSN:-postgres://postgres:password@postgres:5432/analytics?sslmode=disable}
    depends_on:
      migrate:
        condition: service_completed_successfully
      worker:
        condition: service_started
      postgres:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always
    networks:
      - analytics_net

networks:
  analytics_net:
    driver: bridge

volumes:
  postgres_data:
